### ISSUE TITLE
How to style components

### ISSUE THREAD

**Issue by chris-pearce** [fedordead/vanilla-ui#5]
Just a few questions around styling:
1. Do we only do structural/state styling i.e. no cosmetics so that the lib is un-opinionated when it comes to styles making it easier to consume? And perhaps offer a _theme_ where all the cosmetic styling is separate to the structural/state styling? **Or** just bake in the cosmetic styling?
2. Do we make sure all components have zero styling dependencies and that they don't share styles with other components? A minimal amount of base styles will be needed, do we have those styles separate to the component as the only dependency a component needs or bake them into the component?
3. What guidelines do we write CSS to?

**Comment by bnhovde** [comment]
Personal opinion: 
1. Going with the generic pluggable components approach I love the idea of a un-opinionated, functional & accessible base with a simple optional theme added on top.
2. I like the idea of zero dependencies.
   I remember talking to @davislurve about this lately, and I can't remember if this was something you guys already were using, but having only a "base" style sheet with resets etc and everything shared (such as baselines and font stuff) as includes is something we've tried out at work lately. Here's an example of what I mean in action from [this article](https://24ways.org/2015/beyond-the-style-guide/): 

```
.summary {
    margin-bottom: ($baseline * 4)
}

.summary__title {
    @include font-family(display-serif);
    @include font-size(title);
    color: palette(neutral, dark);
    margin-bottom: ($baseline * 4);
    border-top: $rule-height solid palette(primary, purple);
    padding-top: ($baseline * 2);
}

.summary__position {
    @include font-family(display-sans, 300);
    color: palette(neutral, mid);
}

.summary__body {
    @include font-family(text-serif);
    @include font-size(body);
    margin-bottom: ($baseline * 2);
}

.summary__meta {
    @include font-family(text-sans);
    @include font-size(caption);
}
```

Saying that, I'm open to suggestions here. I can't quite get my head around if all of this will affect the base css (the purely functional styling) or just the "theme theme".

3: Open to suggestions. I'm easy!

**Comment by chris-pearce** [comment]
1. I think that's the way to go re no cosmetics baked in then we can look at adding themes later.
2. We could look at using **Shell** (will be public today/tomorrow) which is a CSS lib developed at Campaign Monitor which will provide all the Base styles including resets/normalise, Layout Modules like Flexbox _grid_, _media object_, a bunch of handy Helpers, sensible Sass settings, some good Sass functions & mixins, etc. I'm working on a Docs site which will make understanding it easier. If we go with **Shell** then that'll come in via an NPM module which we import from our master stylesheet, we may need additional base like shared styles but should be kept to a bare minimum. Then everything else encapsulated in the component. I like the look of the example Sass above :+1:.
3. I've got these: https://github.com/chris-pearce/css-guidelines but they need updating to reflect the guidelines we use at CM as they're really dated, which I'll do today/tomorrow. Or we can use 3rd party guidelines like: http://cssguidelin.es/?

**Comment by chris-pearce** [comment]
Are we going responsive with our components? If so we'll have to support touch events.

**Comment by bnhovde** [comment]
1. Agreed.
2. Shell sounds interesting. I'd be up to try it out.
3. http://cssguidelin.es/ is pretty much what we use at work. Will the CM guidelines differ a lot from these? I think as long as everyone writes similar css I'd be happy. (Have any of you had any luck implementing comb css or similar before? I found it a great idea but it didn't play ball with the BEM syntax)

Responsive: I think it'd make the components more attractive for sure.

**Comment by DaveOrDead** [comment]
I'm down with Shell, although bias as it was made at work ;) seems like it would be a good fit though. Also means we get the benefit of another smart dev trying it out / fine tuning it

**Comment by chris-pearce** [comment]
I'll get Shell in the public CM repo so @bnhovde can check it out. Hopefully the Docs site will be ready soon.

> http://cssguidelin.es/ is pretty much what we use at work. Will the CM guidelines differ a lot from these?

They're very similar and they also apply the same or similar namespacing as [**ITCSS**](http://itcss.io/), see: http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/.

Can take a look here: https://github.com/chris-pearce/css-guidelines/.

**Comment by chris-pearce** [comment]
@bnhovde Shell is here: https://github.com/campaignmonitor/shell if you want to take a look? Cheers.

**Comment by bnhovde** [comment]
Excellent. This all looks very interesting. I have yet to dive in for a proper look but skimming through the repo I haven't seen anything I disagree with.

I'll have a more in-depth look tomorrow.

**Comment by bnhovde** [comment]
I've had a proper look at shell now. It looks very smart, lots of clever approaches in there and I love the commented documentation. I also like the namespaces used for the different helper modules. Nice work!

I'm very curious about the following:
1. What is the difference between the side-by-side module and a 2-cell row using the grid module?
2. This one doesn't really related to Shell per say: What is your experience with rems? Personally I've been through several iterations of love & hate. I like the idea, but it never truly clicked for me. I've used rems for the last 2-3 years, until recently when a colleague at work told me he'd gone back to pixels and I challenged me to justify using them. I tried, but kept debunking my own reasons:

**\- Changing the body font-size and seeing everything scale to adjust:** I've never seen this kind of linear scaling work in practice without breaking everything, especially in any remotely complex UI. It also goes against any kind of modular approach since every module is affected by a global css rule.

**\- Pixels mean nothing any more now that screens fit X pixels into an old pixel:** This may be true, but I still know roughly how big a 16px font will appear to the user, even if the new iPad pro fits 150 pixels in each old px. I don't know how big 2.1, 1.45 or 12 rems are, It just doesn't mean anything to me. Aside from serving up different image ppi's, do I really need to worry about screen densities?

**\- The zoom and media query px bugs** Resolved in all modern browsers

**\- User font-size settings** This is one that's actually valid, using px values will override user scaling, but isn't this is what the browser zoom functionality is for? It scales websites a lot nicer than just setting the base font size. I don't know enough about use cases here to be honest.

After writing this I [found an article that goes into it further](https://mindtheshift.wordpress.com/2015/04/02/r-i-p-rem-viva-css-reference-pixel/), but a couple of the comments gave some valid points against what I'm talking about here, pointing out that not all devices (such as e-book readers) will have built-in zooming) 

Anyway, that's it for my rem-rant. I'm just curious what you two both think as I may have missed other reasons why they are a good thing. I'm 100% happy to use them as I'm used to it by now, but I thought it'd be interesting to hear what two seasoned FEDs thought about it. With sass these days we rarely see px or rem values outside of settings files anyway as they're usually hidden behind some shared sizing-unit variable, but I still feel like we were lied to by tons of articles promising wondrous benefits.

Back to Shell. I think it looks awesome, more than happy to use it. :+1: Nice work guys!

**Comment by DaveOrDead** [comment]
Haha it's funny you should mention the rem thing, I brought this up at a Frontend meeting the other week. CP answered it pretty well so I'll leave that to him :)

As for the grid vs side by side there isn't a huge difference. The grid is more designed to work with percentage based widths whilst side by side is more akin to the "media object" with more flexibility around switching alognment / order and uses auto width. It's just that the name didn't sit that well with us.

**Comment by chris-pearce** [comment]
Glad you like Shell @bnhovde :smile:. I'm really happy with it and looking forward to putting it through its paces in the next few months and finishing its _Docs_. It no doubt has bugs—most likely in the Flexbox grid—but they'll get fixed fast enough.

As @davislurve said the `rem` v `px` argument came up the other week at work.

![rem v px](https://cloud.githubusercontent.com/assets/1342772/12841777/6549d4cc-cc42-11e5-8d06-357d93d1dfa0.jpg)

Here's my take on it:
- I'm never comfortable overriding (or hijacking) browser settings that a browser user can set, and this happens when we use `px` for font sizing as it prevents a user from changing their browser's font size, done in Chrome, like so:
  
  <img width="413" alt="screen shot 2016-02-05 at 7 23 44 pm" src="https://cloud.githubusercontent.com/assets/1342772/12841203/34fee7ca-cc3e-11e5-847d-5b11d964093b.png">
  
  Yes _Page zoom_ is also a setting and is what most users use but still, I believe we should respect all users. And like you mentioned not all devices have zooming. I like to build things that are as far reaching and future proofed as possible.
- I think most developers and designers want to use an absolute unit like `px` because they want to be, well, _pixel perfect_. My take on that is that we're building for a medium that is fluid, responsive, and dynamic and we should be embracing that, not trying to control things at the pixel level, our energy is best spent elsewhere. Relative units like `rem` are better suited to the Web, I feel.
- Using Sass or a library like Shell you're always adding a `px` like number due to using a Sass function or mixin behind the scenes, e.g. `font-size: rem(22);`. So its like using `px` anyway from an authoring point of view.
- I still think using the `em` unit for viewport width media queries is still a valid thing? Although I'd have to test this one out. This article was the go to article for this but it was written in 2012: http://blog.cloudfour.com/the-ems-have-it-proportional-media-queries-ftw/. Shell is using `em`s for its breakpoint settings: https://github.com/campaignmonitor/shell/blob/master/src/_settings.scss#L405-L415.

I've personally never had any issues using relative units like `rem` or `em`, and sometimes its good to flip this argument around and ask yourself _“what is wrong with using `rem`?”_.

**Comment by DaveOrDead** [comment]
That should be a blog post

**Comment by bnhovde** [comment]
Agreed. Very well put, you've convinced me it's the way to go. I still don't like rems, but I see why it's a necessity.

I love the px->rem mixin idea. For some reason I've never thought of using it that way, but instead turned REM's into px for older browsers. Aside from the pipe-dream of global font scaling this was my biggest quarrel with REMs.

+1 on the blog post.

**Comment by DaveOrDead** [comment]
Seem to be agreed on approach on minimal functional styling for base components with theme optional so closing issue
